version: '3.8'

services:

  database:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    container_name: db

  backend:
    image: carlodipalma/decks-backend:latest
    volumes:
      - static_value:/app/static/
    depends_on:
      - database
    env_file:
      - .env
    restart: always
    container_name: backend

  frontend:
    image: carlodipalma/decks-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
    container_name: frontend

  nginx:
    image: carlodipalma/foodgram_gateway:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/dist:/usr/share/nginx/html/:rw
      - static_value:/var/html/static/
    depends_on:
      - frontend
    container_name: nginx

volumes:
  postgres_data:
  static_value: