version: '3.8'

volumes:
  postgres_data:
  static:

services:

  database:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: database

  backend:
    image: carlodipalma/loyalty-backend:latest
    volumes:
      - static:/backend_static
    depends_on:
      - database
    env_file:
      - .env
    restart: always
    container_name: backend

  frontend:
    container_name: frontend
    image: carlodipalma/loyalty-frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend


  nginx:
    container_name: nginx
    image: carlodipalma/loyalty-nginx:latest
    ports:
      - 8000:80
    volumes:
      - static:/static/
    depends_on:
      - backend
      - frontend

