version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/customer-loyalty-full
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - customer-loyalty-full:/data/db

volumes:
  customer-loyalty-full:
