name: Test workflow

on:
  workflow_dispatch

jobs:

  deploy:
    name: Deploy on a production server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy docker-compose.production.yml via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_NEW_PRIVATE_KEY }}
          source: "docker-compose.production.yml"
          target: "/"